authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'mainapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.urls import re_path
from django.views.generic import RedirectView

import mainapp.views as mainapp
from geekshop import settings

urlpatterns = [
    re_path(r'^$', mainapp.main, name='main'),
    re_path(r'^products/', include('mainapp.urls', namespace='products')),
    re_path(r'^contact/', mainapp.contact, name='contact'),
    re_path(r'^auth/verify/google/oauth2/', include("social_django.urls", namespace="social")),
    re_path(r'^auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
    re_path(r'^admin/', include('adminapp.urls', namespace='admins')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

# for url in urlpatterns:
#     logging.debug(str(url))

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'


urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f'{self.name}({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def main(request):
    title = 'Главная'
    products_list = Product.objects.all()[:4]
    basket = get_basket(request.user)
    content = {
        'title': title,
        'products': products_list,
    }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    basket = get_basket(request.user)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')

        paginator = Paginator(products, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products.html', content)


def contact(request):
    title = 'Контакты'
    basket = get_basket(request.user)
    content = {
        'title': title,
    }
    return render(request, 'mainapp/contact.html', content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

    return same_products


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)

# def products(request, pk=None):
#     title = 'Продукты'
#     links_menu = ProductCategory.objects.all()
#
#     basket = []
#     if request.user.is_authenticated:
#         basket = Basket.objects.filter(user=request.user)
#
#     if pk is not None:
#         if pk == 0:
#             products = Product.objects.all().order_by('price')
#             category = {'name': 'все'}
#         else:
#             category = get_object_or_404(ProductCategory, pk=pk)
#             products = Product.objects.filter(category__pk=pk).order_by('price')
#
#         content = {
#             'title': title,
#             'links_menu': links_menu,
#             'category': category,
#             'products': products,
#             'basket': basket,
#         }
#
#         return render(request, 'products_list.html', content)
#
#     products_list = Product.objects.all()[::3]
#     content = {
#         'title': title,
#         'products': products_list,
#         'links_menu': ProductCategory.objects.all()
#     }
#     if pk:
#         product_category = ProductCategory.objects.get(pk=pk)
#         # content['category'] = product_category, products_list
#         content['products'] = Product.objects.filter(category__pk=pk)
#     return render(request, 'products.html', content)


# def products(request, pk=None):
#     print(pk)
#
#     title = 'продукты'
#     links_menu = ProductCategory.objects.all()
#     products_list = Product.objects.all()[::3]
#
#     content = {'title': title, 'links_menu': links_menu, 'products_list': products_list}
#     return render(request, 'products.html', content)


# def products(request, pk=None):
#     print(pk)
#     title = 'Продукты'
#     products_list = Product.objects.all()[:12]
#     content = {
#         'title': title,
#         'products': products_list
#     }
#     if pk:
#         product_category = ProductCategory.get_object_or_404(pk=pk)
#         content['product'] = product_category, products_list
#     return render(request, 'products.html', content)


# def products_all(request):
#     title = 'Все товары'
#     links_menu = [
#         {'href': 'products', 'name': 'All series'},
#         {'href': 'products/', 'name': '12v series'},
#         {'href': 'products_18v', 'name': '18v series'},
#         {'href': 'products_2436v', 'name': '24-36v series'},
#     ]
#     products_list = Product.objects.all()[:4]
#     content = {
#         'title': title, 'products': products_list
#
#     }
#     return render(request, 'products.html', content)
#
#
# def products_12v(request):
#     links_menu = [
#         {'href': 'products_all', 'name': 'All series'},
#         {'href': 'products_12v', 'name': '12v series'},
#         {'href': 'products_18v', 'name': '18v series'},
#         {'href': 'products_2436v', 'name': '24-36v series'},
#     ]
#     content = {
#         'links_menu': links_menu
#     }
#     return render(request, 'products.html', content)
#
#
# def products_18v(request):
#     links_menu = [
#         {'href': 'products_all', 'name': 'All series'},
#         {'href': 'products_12v', 'name': '12v series'},
#         {'href': 'products_18v', 'name': '18v series'},
#         {'href': 'products_2436v', 'name': '24-36v series'},
#     ]
#     content = {
#         'links_menu': links_menu
#     }
#     return render(request, 'products.html', content)
#
#
# def products_2436v(request):
#     links_menu = [
#         {'href': 'products_all', 'name': 'All series'},
#         {'href': 'products_12v', 'name': '12v series'},
#         {'href': 'products_18v', 'name': '18v series'},
#         {'href': 'products_2436v', 'name': '24-36v series'},
#     ]
#     content = {
#         'links_menu': links_menu
#     }
#     return render(request, 'products.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>
            {% block title%}
                HoT - {{ title|title }}
            {% endblock %}
        </title>
        
        {% block css %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main_style.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">
        {% endblock %}

        {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/orders_scripts.js' %}"></script>
        {% endblock %}
    </head>

    <body>
        <div class="container">
            {% block page_header %}
            <div class="header">
                <a href="{% url 'main' %}" class="header_logo"></a>
                <h1>Heap of Tools</h1>
                <p>Pour homme...</p>
            </div>
            {% include 'includes/inc_navbar.html' %}
            {% endblock %}
            {% block page_content %}
            {% endblock %}
            <div class="clr"></div>
        </div>
        {% block footer %}
        <div class="footer">
            <div class="contact_us">
                <div class="contact_us_head">CONTACT US</div>
                <p class="contact_adress">132A Bridge Road Richmond VIC Australia.<br><br> Talk to us on 1300 132 <a class="contact_mail" href="#">info@heapoftools.com</a></p>
            </div>
            <div class="useful_inf">
                <div class="useful_inf_head">USEFUL INFORMATION</div>
                <div class="useful_links">
                    <div class="left">
                        <li><a href="#">Sales terms</a></li>
                        <li><a href="#">Customer care</a></li>
                        <li><a href="#">Delivery</a></li>
                    </div>
                    <ul class="right">
                        <li><a href="#">Architect accounts</a></li>
                        <li><a href="#">Careers</a></li>
                        <li><a href="#">Exchanges and returns</a></li>
                    </ul>
                </div>
            </div>
            <div class="Lets_Stay">
                <div class="Lets_Stay_head">LET'S STAY IN TOUCH!</div>
                <p class="lets_content">Suscribe to know about our latest news, products special offers just for suscribers.</p>
                <form class="subscribe_email clearfix" action="">
                    <input type="text" class="text" name="email" placeholder="   Your email address" size="35" style="height: 41px;">
                    <svg class="ico_send" display="none">
                                        <symbol id="icon_telegram" viewBox="0 0 448 512">
                                            <path fill="currentColor" d="M446.7 98.6l-67.6 318.8c-5.1 22.5-18.4 28.1-37.3 17.5l-103-75.9-49.7 47.8c-5.5 5.5-10.1 10.1-20.7 10.1l7.4-104.9 190.9-172.5c8.3-7.4-1.8-11.5-12.9-4.1L117.8 284 16.2 252.2c-22.1-6.9-22.5-22.1 4.6-32.7L418.2 66.4c18.4-6.9 34.5 4.1 28.5 32.2z"/>
                                        </symbol>
                                    </svg>
                    <div class="social telegram">
                        <a href="#">
                            <svg>
                                <use xlink:href="#icon_telegram"></use>
                            </svg>
                        </a>
                    </div>

                </form>
            </div>
            <div class="footer_bottom">
                <div class="left">© Heap of Tools 2020. All Rights Reserved.</div>
                <ul class="center">
                    <li class="footer_soc_link">
                        <a href="#"><img src="{% static 'img/f.png'%}" alt="fb"></a>
                    </li>
                    <li class="footer_soc_link">
                        <a href="#"><img src="{% static 'img/vk.png' %}" alt="vk"></a>
                    </li>
                    <li class="footer_soc_link">
                        <a href="#"><img src="{% static 'img/pinterest.png' %}" alt="pinterest"></a>
                    </li>
                    <li class="footer_soc_link">
                        <a href="#"><img src="{% static 'img/twitter.png' %}" alt="twitter"></a>
                    </li>
                </ul>
                <div class="right">Terms & Conditions / Privacy policy & Cookies</div>
            </div>
        </div>
        {% endblock %}
    </body>
</html> 

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

{% block page_header %}
{{ block.super }}
{% endblock %}

{% block page_content %}
<div class="contact_main">
    <div class="contact_head">
        <h1>Свяжитесь с нами</h1>
    </div>
    <div class="contact_places">
        <div class="contact_center_board">
            <div class="medium_board board_1">
                <div class="img_marker"><img src="img/marker.png" alt=""></div>
                <div class="location_name">California</div>
                <div class="address">
                    <br>
                    <h6 class="small_head">Phone:</h6>
                    <a href="#" class="contact_phone">1900 - 1234 - 5678</a>
                    <br>
                    <h6 class="small_head">Email:</h6>
                    <a href="#" class="contact_email">info@interior.com</a>
                    <br>
                    <h6 class="small_head">Address:</h6>
                    <p class="contact_address">12 W 1st St, 90001 Los Angeles, California</p>
                </div>
            </div>
            <div class="medium_board board_2">
                <div class="img_marker"><img src="img/marker.png" alt=""></div>
                <div class="location_name">California</div>
                <div class="address">
                    <br>
                    <h6 class="small_head">Phone:</h6>
                    <a href="#" class="contact_phone">1900 - 1234 - 5678</a>
                    <br>
                    <h6 class="small_head">Email:</h6>
                    <a href="#" class="contact_email">info@interior.com</a>
                    <br>
                    <h6 class="small_head">Address:</h6>
                    <p class="contact_address">12 W 1st St, 90001 Los Angeles, California</p>
                </div>
            </div>
            <div class="medium_board board_3">
                <div class="img_marker"><img src="img/marker.png" alt=""></div>
                <div class="location_name">California</div>
                <div class="address">
                    <br>
                    <h6 class="small_head">Phone:</h6>
                    <a href="#" class="contact_phone">1900 - 1234 - 5678</a>
                    <br>
                    <h6 class="small_head">Email:</h6>
                    <a href="#" class="contact_email">info@interior.com</a>
                    <br>
                    <h6 class="small_head">Address:</h6>
                    <p class="contact_address">12 W 1st St, 90001 Los Angeles, California</p>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block footer %}
{{ block.super }}
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

{% block page_header %}
{{ block.super }}
{% endblock %}

{% block page_content %}
<div class="main">
    <div class="welcome_message">
        <h2>Приветствуем, дорогой покупатель!</h2>
        <h3>
            Рады видеть вас в нашем интернет-магазине!<br> В нашем каталоге мировые и российские производители:
            Bosch, DeWALT, AEG, Metabo.<br> Подтверждение — сертификаты официального дилера и отзывы наших
            покупателей!
        </h3>
    </div>
    <div class="main_menu">
        <a href="#" class="main_menu_left">Скидки</a>
        <a href="#" class="main_menu_left">Новинки</a>
        <a href="{% url 'products:category' 0 %}" class="main_menu_right">Смотреть все ></a>
    </div>
    <div class="hot_deal clearfix">
        {% for product in products %}
        <div class="block">
            <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="">
                <div class="text">
                    <img src="{% static 'img/icon-hover.png' %}" alt="img">
                    <h3>{{ product.category }}</h3>
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block footer %}
{{ block.super }}
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

{% block page_header %}
{{ block.super }}
{% endblock %}

{% block page_content %}
<div class="product_details">
    <div class="product_links clearfix">
        {% include 'includes/inc_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}"
                     alt="{{ product.short_desc }}">
            </div>
            <div class="details_mini">
                <div class="block">
                    <a href="#">
                        <img src="/media/{{ product.image }}" alt="вариант 1">
                    </a>
                </div>
                <div class="block">
                    <a href="#">
                        <img src="/media/{{ product.image }}" alt="вариант 2">
                    </a>
                </div>
                <div class="block">
                    <a href="#">
                        <img src="/media/{{ product.image }}" alt="вариант 3">
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-head">{{ product.name }}</h3>
            <br><br>
            <p class="price"> {{ product.price }} <span>руб</span></p>
            <br><br>
            <div class="description_text">
                {{ product.description }}
            </div>
            <a href="{% url 'basket:add' product.pk %}" class="buy_btn" style="vertical-align:middle"><span>
                Купить</span>
            </a>
        </div>
    </div>

</div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block css %}
{{ block.super }}
{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

{% block page_header %}
{{ block.super }}
{% endblock %}

{% block page_content %}
<div class="products_main">
    <div class="product_links clearfix">
        {% include 'includes/inc_menu.html' %}
    </div>
    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image }}">
            </div>
            <div class="details_mini">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.name }}</h3>
            <br><br>
            <h3 class="red">Горячее предложение</h3>
            <br>
            <p class="price">{{ hot_product.price }} <span>руб</span></p>
            <br>
            <div class="description_text">
                {{ hot_product.description }}
            </div>
            <br>
            <a class="hot_deal_button" href="{% url 'basket:add' hot_product.pk %}" >
                <span>Купить</span> </a>
            
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{{ block.super }}
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block js %}
{{ block.super }}
{% endblock %}

{% block page_content %}
<div class="details">
    <div class="product_links clearfix">
        {% include 'includes/inc_menu.html' %}
    </div>
    <div class="products_deal">
        <div class="category-products clearfix">
            <div class="products_list">
                <div class="title clearfix">
                    <h2>Категория: "{{ category.name|title }}"</h2>
                    <div class="paginator clearfix">
                        {% if products.has_previous %}
                        <a class="previous_a" href="{% url 'products:page' category.pk products.previous_page_number %}">
                            < </a>
                                {% endif %}
                                <span class="current">
                                    страница {{ products.number }} из
                                    {{ products.paginator.num_pages }}
                                </span>
                                {% if products.has_next %}
                                <a class="next_a" href="{% url 'products:page' category.pk products.next_page_number %}">
                                    >
                                </a>
                                {% endif %}
                    </div>
                </div>
            </div>

            {% for product in products %}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}"><img class="product_img" src="/media/{{ product.image }}" alt="">
                    <div class="text">
                        <img class="icon_hover" src="{% static '/img/icon-hover.png' %}" alt="img">
                        <h3>{{ product.category }}</h3>
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}